---

- hosts: all
  tasks:
  - name: Find out what is going on
    ansible.builtin.command: ps aux > /tmp/processes.txt
    delegate_to: 127.0.0.1
  - name: Run the socat
    ansible.builtin.command: socat -h
    delegate_to: 127.0.0.1
  - name: Create some local file
    local_action: ansible.builtin.command touch /tmp/awesome_file
  - name: Do something local
    local_action: ansible.builtin.command ssh-keygen -b 2048 -t rsa -f /tmp/sshkey -q -N ""
  - name: Creating an empty file
    remote_user: vagrant
    file:
      path: "/tmp/somefile"
      state: touch
