---

- hosts: all
  tasks:
  - name: blow up
    ansible.builtin.command: abcdefg
    delegate_to: 127.0.0.1
  - name: Create a great file
    ansible.builtin.command: touch /tmp/great_file
    delegate_to: 127.0.0.1
  - name: Create some local file
    local_action: ansible.builtin.command touch /tmp/awesome_file
  - name: Do something local
    local_action: ansible.builtin.command ssh-keygen -b 2048 -t rsa -f /tmp/sshkey -q -N ""
